"""
backend/agent/session.py

Session state contract for the Wafrivet Field Vet ADK agent.

All ADK tools read from and write to this shared state via ToolContext.
Session state is the single source of truth for the conversation — no tool
may ask the farmer for information that already exists in state.

The WafrivetSessionState TypedDict defines the structure; INITIAL_STATE is
the template passed when creating a new session via InMemorySessionService
or Vertex AI Agent Engine.
"""

from __future__ import annotations

from typing import Any, Optional, TypedDict


class CartItem(TypedDict):
    """A single product line item in the farmer's cart."""

    product_id: str
    product_name: str
    quantity: int
    unit_price: float   # Naira
    subtotal: float     # unit_price × quantity, in Naira


class WafrivetSessionState(TypedDict, total=False):
    """
    Full session state schema for a Wafrivet Field Vet conversation.

    Every field is optional (total=False) because a fresh session starts
    with no confirmed disease, state, or cart. Fields are populated
    progressively as the conversation unfolds across multiple turns.

    Attributes:
        farmer_state:
            The farmer's Nigerian state (title-case, no "State" suffix,
            e.g. "Rivers"). Set by update_location; read by recommend_products
            and manage_cart to avoid re-asking the farmer.
        farmer_phone:
            E.164 phone number (e.g. "+2348012345678"). May be provided
            upfront via the initial_state dict or captured during the session.
        active_species:
            The animal species being discussed (e.g. "Goats", "Cattle").
            Inferred from the top search_disease_matches result.
        confirmed_disease:
            The disease_name from the top search_disease_matches result.
            Stored so recommend_products can use it without re-querying.
        confirmed_disease_id:
            UUID of the disease_content row for the confirmed disease.
        confirmed_disease_severity:
            risk_level from the confirmed disease row:
            "low" | "medium" | "high" | "critical". Used to trigger
            escalation language when severity is "critical".
        cart_items:
            Current line items in the farmer's active cart.
        cart_total:
            Running total in Naira. Updated by manage_cart on every
            add/remove/clear operation.
        checkout_url:
            Paystack authorization_url generated by generate_checkout_link.
            Stored so the WebSocket bridge can broadcast it to the frontend.
        location_source:
            Either "voice" (farmer stated their location) or "auto"
            (location detected automatically by the frontend). Logged for
            analytics but not functionally decisive.
    """

    farmer_state: Optional[str]
    farmer_phone: Optional[str]
    active_species: Optional[str]
    confirmed_disease: Optional[str]
    confirmed_disease_id: Optional[str]
    confirmed_disease_severity: Optional[str]
    cart_items: list[CartItem]
    cart_total: float
    checkout_url: Optional[str]
    location_source: str
    farmer_lat: Optional[float]
    farmer_lon: Optional[float]
    farmer_lga: Optional[str]
    # Phase 3 additions
    last_search_results: list[Any]   # Cached search_products results for add_to_cart
    is_scanning_product: bool        # True while identify_product_from_frame is active
    last_order_reference: Optional[str]  # Most recent order reference from place_order


# ---------------------------------------------------------------------------
# Default state template
# Tools must never mutate this dict directly — copy it with {**INITIAL_STATE}
# when creating a new session.
# ---------------------------------------------------------------------------

INITIAL_STATE: dict[str, Any] = {
    "farmer_state": None,
    "farmer_phone": None,
    "active_species": None,
    "confirmed_disease": None,
    "confirmed_disease_id": None,
    "confirmed_disease_severity": None,
    "cart_items": [],
    "cart_total": 0.0,
    "checkout_url": None,
    "location_source": "voice",
    "farmer_lat": None,
    "farmer_lon": None,
    "farmer_lga": None,
    # Phase 3 additions
    "last_search_results": [],
    "is_scanning_product": False,
    "last_order_reference": None,
}
